workflows:
  magic8_release:
    name: Magic8 Release iOS & Android
    environment:
      flutter: stable
      xcode: latest
      vars:
        AI_BASE_URL: ${AI_BASE_URL}
        AI_KEY: ${AI_KEY}
        AI_MODEL: gpt-4o-mini
    scripts:
      - flutter --version
      - flutter create . --org com.morozov
      - flutter pub get
      - dart run flutter_launcher_icons
      - |
          # iOS: add microphone & speech permissions
          /usr/libexec/PlistBuddy -c 'Add :NSSpeechRecognitionUsageDescription string "Для распознавания вопросов голосом"' ios/Runner/Info.plist || /usr/libexec/PlistBuddy -c 'Set :NSSpeechRecognitionUsageDescription "Для распознавания вопросов голосом"' ios/Runner/Info.plist
          /usr/libexec/PlistBuddy -c 'Add :NSMicrophoneUsageDescription string "Для записи вашего вопроса"' ios/Runner/Info.plist || /usr/libexec/PlistBuddy -c 'Set :NSMicrophoneUsageDescription "Для записи вашего вопроса"' ios/Runner/Info.plist
          # Android: add RECORD_AUDIO permission if missing
          FILE=android/app/src/main/AndroidManifest.xml
          if ! grep -q 'RECORD_AUDIO' "$FILE"; then
            sed -i '' '1,10s#<manifest#<manifest>\n    <uses-permission android:name="android.permission.RECORD_AUDIO"/>#' "$FILE" || true
          fi
      - flutter build apk --debug --dart-define=AI_BASE_URL=$AI_BASE_URL --dart-define=AI_KEY=$AI_KEY --dart-define=AI_MODEL=$AI_MODEL
      - flutter build apk --release --dart-define=AI_BASE_URL=$AI_BASE_URL --dart-define=AI_KEY=$AI_KEY --dart-define=AI_MODEL=$AI_MODEL
      - flutter build ios --release --no-codesign --dart-define=AI_BASE_URL=$AI_BASE_URL --dart-define=AI_KEY=$AI_KEY --dart-define=AI_MODEL=$AI_MODEL
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/ios/iphoneos/*.app
