workflows:
  magic8-release:
    name: Magic8 Release iOS & Android
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      java: 11
      groups:
        - keystore_credentials
        - appstore_credentials
      vars:
        AI_BASE_URL: "https://your-ai-server.com"
        AI_KEY: "your_ai_key"
        AI_MODEL: "gpt-4"
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter create . --org com.morozov
          flutter pub get
          dart run flutter_launcher_icons

          # Увеличиваем память для Gradle и включаем AndroidX
          mkdir -p android
          echo "org.gradle.jvmargs=-Xmx4608m -Dkotlin.daemon.jvm.options=-Xmx1024m -Dfile.encoding=UTF-8" >> android/gradle.properties
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties

      - name: Build Android debug (arm64 only)
        script: |
          flutter build apk --debug --target-platform=android-arm64 \
            --dart-define=AI_BASE_URL=$AI_BASE_URL \
            --dart-define=AI_KEY=$AI_KEY \
            --dart-define=AI_MODEL=$AI_MODEL

      - name: Build Android release (split-per-abi)
        script: |
          flutter build apk --release --split-per-abi \
            --dart-define=AI_BASE_URL=$AI_BASE_URL \
            --dart-define=AI_KEY=$AI_KEY \
            --dart-define=AI_MODEL=$AI_MODEL

      - name: Build iOS release
        script: |
          flutter build ios --release --no-codesign \
            --dart-define=AI_BASE_URL=$AI_BASE_URL \
            --dart-define=AI_KEY=$AI_KEY \
            --dart-define=AI_MODEL=$AI_MODEL

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.ipa
      - build/**/outputs/**/app-release.aab
