workflows:
  build_app:
    name: Build Android & iOS (Simple)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        AI_BASE_URL: "https://restless-haze-e206.1808812.workers.dev/"
    scripts:
      - flutter --version
      - flutter create . --org com.morozov
      - flutter pub get
      # Gradle: больше памяти + AndroidX
      - mkdir -p android
      - echo "org.gradle.jvmargs=-Xmx4608m -Dkotlin.daemon.jvm.options=-Xmx1024m -Dfile.encoding=UTF-8" >> android/gradle.properties
      - echo "android.useAndroidX=true" >> android/gradle.properties
      - echo "android.enableJetifier=true" >> android/gradle.properties
      # Генерация иконок (после создания ios/android)
      - dart run flutter_launcher_icons
      # Android debug (arm64 только)
      - flutter build apk --debug --target-platform=android-arm64 --dart-define=AI_BASE_URL=$AI_BASE_URL
      # Android release (разделение по ABI)
      - flutter build apk --release --split-per-abi --dart-define=AI_BASE_URL=$AI_BASE_URL
      # iOS release без подписания
      - flutter build ios --release --no-codesign --dart-define=AI_BASE_URL=$AI_BASE_URL
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/iphoneos/*.app
