workflows:
  build-app:
    name: Build Android & iOS (Simple)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        AI_BASE_URL: "https://restless-haze-e206.1808812.workers.dev/"
    scripts:
      - name: Generate launcher icons
        script: |
          flutter pub get
          dart run flutter_launcher_icons

      - name: Build Android debug
        script: |
          flutter build apk --debug --dart-define=AI_BASE_URL=$AI_BASE_URL

      - name: Build Android release
        script: |
          flutter build apk --release --dart-define=AI_BASE_URL=$AI_BASE_URL

      - name: Build iOS release (no codesign)
        script: |
          flutter build ios --release --no-codesign --dart-define=AI_BASE_URL=$AI_BASE_URL

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.ipa
