workflows:
  magic8-workflow:
    name: Magic 8 Ball App
    environment:
      flutter: stable
      vars:
        AI_BASE_URL: $AI_BASE_URL
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Generate platform folders
        script: flutter create .
      - name: Add Android permissions
        script: |
          sed -i '/<application/i\    <uses-permission android:name="android.permission.RECORD_AUDIO"/>' android/app/src/main/AndroidManifest.xml
      - name: Add iOS permissions
        script: |
          plutil -insert NSSpeechRecognitionUsageDescription -string "Для распознавания голосовых вопросов" ios/Runner/Info.plist
          plutil -insert NSMicrophoneUsageDescription -string "Для записи вашего вопроса" ios/Runner/Info.plist
      - name: Build APK
        script: flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
